### ISSUE TITLE
compressed coal recipe overrides recipe of block of coal

### ISSUE THREAD

**Issue by krjencik** [VoidCallerZ/UltimateCompression_1.18.1#3]
Not sure where to write this.

MInecraft 1.19.1. 

I want also blocks of coal, what do i do? (i guess the mechanic is same for other materials that have blocks...)

**Comment by VoidCallerZ** [comment]
Sorry for the late reply, I was on a 2 week vacation. Are you still having the same issue, because on the last version I tested it worked fine. 
For compressed blocks of coal you currently need the compressed version of the material. So you need 9 compressed coal to make 1 compressed block of coal.
